import {IFieldConstraints} from './types';

export class CronConstants {
  /* istanbul ignore next - should never be called */
  constructor() {
    throw new Error('This class is not meant to be instantiated.');
  }

  static get constraints(): IFieldConstraints {
    return {
      second: {min: 0, max: 59, chars: []},
      minute: {min: 0, max: 59, chars: []},
      hour: {min: 0, max: 23, chars: []},
      dayOfMonth: {min: 1, max: 31, chars: ['L']},
      month: {min: 1, max: 12, chars: []},
      dayOfWeek: {min: 0, max: 7, chars: ['L']},
    };
  }

  static get daysInMonth(): number[] {
    return [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  }
}

// todo?
// export const expressions = {
//   '/every-second': '* * * * * *',
//   '/every-minute': '* * * * *',
//   '/every-1-minute': '* * * * *',
//   '/every-2-minutes': '*/2 * * * *',
//   '/every-even-minute': '*/2 * * * *',
//   '/every-uneven-minute': '1-59/2 * * * *',
//   '/every-3-minutes': '*/3 * * * *',
//   '/every-4-minutes': '*/4 * * * *',
//   '/every-5-minutes': '*/5 * * * *',
//   '/every-five-minutes': '*/5 * * * *',
//   '/every-6-minutes': '*/6 * * * *',
//   '/every-10-minutes': '*/10 * * * *',
//   '/every-ten-minutes': '*/10 * * * *',
//   '/every-15-minutes': '*/15 * * * *',
//   '/every-fifteen-minutes': '*/15 * * * *',
//   '/every-quarter-hour': '*/15 * * * *',
//   '/every-20-minutes': '*/20 * * * *',
//   '/every-30-minutes': '*/30 * * * *',
//   '/every-hour-at-30-minutes': '30 * * * *',
//   '/every-hour-at-15-30-45-minutes': '15,30,45 * * * *',
//   '/every-half-hour': '*/30 * * * *',
//   '/every-60-minutes': '0 * * * *',
//   '/every-hour': '0 * * * *',
//   '/every-1-hour': '0 * * * *',
//   '/every-2-hours': '0 */2 * * *',
//   '/every-two-hours': '0 */2 * * *',
//   '/every-even-hour': '0 */2 * * *',
//   '/every-other-hour': '0 */2 * * *',
//   '/every-3-hours': '0 */3 * * *',
//   '/every-three-hours': '0 */3 * * *',
//   '/every-4-hours': '0 */4 * * *',
//   '/every-6-hours': '0 */6 * * *',
//   '/every-six-hours': '0 */6 * * *',
//   '/every-8-hours': '0 */8 * * *',
//   '/every-12-hours': '0 */12 * * *',
//   '/hour-range': '0 9-17 * * *',
//   '/between-certain-hours': '0 9-17 * * *',
//   '/every-day': '0 0 * * *',
//   '/daily': '0 0 * * *',
//   '/once-a-day': '0 0 * * *',
//   '/every-night': '0 0 * * *',
//   '/every-day-at-1am': '0 1 * * *',
//   '/every-day-at-2am': '0 2 * * *',
//   '/every-day-8am': '0 8 * * *',
//   '/every-morning': '0 9 * * *',
//   '/every-midnight': '0 0 * * *',
//   '/every-day-at-midnight': '0 0 * * *',
//   '/every-night-at-midnight': '0 0 * * *',
//   '/every-sunday': '0 0 * * SUN',
//   '/every-monday': '0 0 * * MON',
//   '/every-tuesday': '0 0 * * TUE',
//   '/every-wednesday': '0 0 * * WED',
//   '/every-thursday': '0 0 * * THU',
//   '/every-friday': '0 0 * * FRI',
//   '/every-friday-at-midnight': '0 0 * * FRI',
//   '/every-saturday': '0 0 * * SAT',
//   '/every-saturday-and-sunday': '0 0 * * SAT,SUN',
//   '/every-saturday-and-sunday-at-noon': '0 12 ? * SAT,SUN',
//   '/every-weekday': '0 0 * * 1-5',
//   '/weekdays-only': '0 0 * * 1-5',
//   '/monday-to-friday': '0 0 * * 1-5',
//   '/every-weekend': '0 0 * * 6,0',
//   '/weekends-only': '0 0 * * 6,0',
//   '/every-2-days-at-noon': '0 12 1/2 * ?',
//   '/every-4-days-at-noon': '0 12 1/4 * ?',
//   '/every-7-days': '0 0 * * 0',
//   '/weekly': '0 0 * * 0',
//   '/once-a-week': '0 0 * * 0',
//   '/every-week': '0 0 * * 0',
//   '/every-month': '0 0 1 * *',
//   '/every-month-on-second': '0 1 2 * ?',
//   // '/every-month-on-last-day-at-noon': '0 12 L * ?',
//   // '/every-month-on-second-to-last-day-at-noon': '0 12 L-2 * ?',
//   // '/every-month-on-last-weekday-at-noon': '0 12 LW * ?',
//   // '/every-month-on-last-sunday-at-noon': '0 12 1L * ?',
//   // '/every-month-on-last-monday-at-noon': '0 12 2L * ?',
//   // '/every-month-on-nearest-weekday-to-1st-of-month-at-noon': '0 12 1W * ?',
//   // '/every-month-on-nearest-weekday-to-15th-of-month-at-noon': '0 12 15W * ?',
//   // '/every-month-on-first-monday-of-month-at-noon': '0 12 ? * 2#1',
//   // '/every-month-on-first-friday-of-month-at-noon': '0 12 ? * 6#1',
//   // '/every-month-on-third-thursday-of-month-at-noon': '0 12 ? * 5#3',
//   '/monthly': '0 0 1 * *',
//   '/once-a-month': '0 0 1 * *',
//   '/every-other-month': '0 0 1 */2 *',
//   '/every-quarter': '0 0 1 */3 *',
//   '/every-6-months': '0 0 1 */6 *',
//   '/every-year': '0 0 1 1 *',
//   '/every-day-at-noon-in-january-only': '0 12 ? JAN *',
//   '/every-day-at-noon-in-june-only': '0 12 ? JUN *',
//   '/every-day-at-noon-in-january-and-june-only': '0 12 ? JAN,JUN *',
//   '/every-day-at-noon-in-january-february-june-november-only': '0 12 ? JAN,FEB,JUN,NOV *',
//   '/every-day-at-noon-between-september-and-december': '0 12 ? 8-11 *',
//   '/every-day-at-noon-between-january-to-march-and-september-to-december': '0 12 ? 0-2,8-11 *',
//
// };
